### ISSUE TITLE
Getting repeated videos

### ISSUE THREAD

**Issue by yshish** [zooniverse/Chimp-Zoo#98] opened 2016-02-17 12:08 UTC
I have been getting the same videos to classify more than once. Usually they come in random but once I got the same one twice in a row. 
I can't tell how many times it happened since I mainly get videos with no animals present.
I noticed other volunteer complaining about the same. 

Some examples:
 - http://talk.chimpandsee.org/#/subjects/ACP00062ny
 - http://talk.chimpandsee.org/#/subjects/ACP0007k1t
 - http://talk.chimpandsee.org/#/subjects/ACP0007bsa
 - http://talk.chimpandsee.org/#/subjects/ACP0007frf
 - http://talk.chimpandsee.org/#/subjects/ACP0006t2k

@srallen Can you look at it please? Thanks!

**Comment by yshish** [comment] 2016-02-18 15:17
It happened again, twice in a row with this video: http://talk.chimpandsee.org/#/subjects/ACP0007iu9 

There was a problem with finishing the classification: when I clicked on the FINISH button after I classified it for the 2nd time, nothing happened. Like if I weren't allowed to do a duplicate classification. The page didn't take me to the location map page but stayed on the video. I tried the button a few times. Then, when I visited my Profile page to make sure the IDs are identical for both, I found the video 4 times there, 1 for each click on the Finish button.

Exactly the same happened with this video: http://talk.chimpandsee.org/#/subjects/ACP0007k1t I got twice in a row 2 days ago. This video appeared 5 times on my Profile page.

The question is: Did it record my classification every time I click on the Finish button (as it appears in the Profile page) or just once?

**Comment by srallen** [comment] 2016-02-18 15:27
Thanks for the info @yshish, sounds like a bug with the classification submission. When this happens, could you check the browser console for errors and let me know what you see?

**Comment by yshish** [comment] 2016-02-18 17:00
It has just happened again! It is a video I classified 2 days ago, and now it came twice in a row again:
http://talk.chimpandsee.org/#/subjects/ACP0007fml

Here is the browser console screenshot after clicking on the Finish button:
![](https://lh3.googleusercontent.com/-A_QHtvz3TwI/VsX4SLfpiII/AAAAAAAAIvw/A9OtfddNMbI/s0-Ic42/ysh_2016-02-18.jpg)

Hope it is helpful.

**Comment by srallen** [comment] 2016-02-18 17:07
Yes, thank you! That should be enough for me to begin debugging.

**Comment by yshish** [comment] 2016-02-18 17:09
Not sure you need it, but more details here:
![](https://lh3.googleusercontent.com/-JifEp2lRYR4/VsX6VxgrC8I/AAAAAAAAIwI/_soWsuGe-qQ/s912-Ic42/ysh_2016-02-18_1.jpg)
![](https://lh3.googleusercontent.com/-8c2vWan_-0I/VsX6VyRmFBI/AAAAAAAAIwQ/a68jGPMq5x0/s912-Ic42/ysh_2016-02-18_20.jpg)
![](https://lh3.googleusercontent.com/-aKNE_MgQctk/VsX6WG4HpkI/AAAAAAAAIwM/niaNkvcAyYE/s912-Ic42/ysh_2016-02-18_21.jpg)

**Comment by srallen** [comment] 2016-02-18 21:13
I fixed `Uncaught TypeError: Cannot read property 'statusMessage' of undefined` but what message we're getting back from the API is an out of subjects response which obviously is incorrect.

**Comment by srallen** [comment] 2016-02-18 21:22
@yshish Could you let me know if you have any more issues getting to the summary (location map) page? I've been running through a few classifications myself and I think fixing the status message fixed that too, but we shouldn't be getting out of subjects responses.

**Comment by jwidness** [comment] 2016-02-19 18:57
I'm not sure if this is related, but [this video](http://talk.chimpandsee.org/#/subjects/ACP00083dp) made it to the official chimp video list and pretty clearly does not contain a chimp.  Do you think this bug could have allowed one person to classify it chimp multiple times?

**Comment by yshish** [comment] 2016-02-19 19:06
I think it could. From my experience, it always counts each classification when repeated.
@srallen can you check this one, please?

BTW, I haven't experienced any repeats since your last post, but I wasn't as active today. I'll let you know if something happens.

**Comment by srallen** [comment] 2016-02-19 19:13
Yeah it's possible if someone ran into the bug that @yshish documented and clicked Finish multiple times. I don't think we're seeing duplicate subjects being served up, but rather duplicate classifications were being sent. I think fixing the status message fixed this duplicate classification issue. 

Unfortunately that means there was a period of a few days where there are duplicates in the raw classifications and this will need to be address in post data analysis. What you'll likely see is set of classifications identical except for the datetime stamp, which would be seconds or less apart from each other if someone was rapidly clicking the Finish button while encountering the bug. 

Fixing this bug, though, revealed a different issue with the API responding with a 'no more subjects' message. This has come up on other projects, so I may need to get another develop to help address that separately. I'll leave this issue open for now and if anyone on the Talk board is reporting duplicate classifications after the fix I pushed yesterday, then please report here. I'll be opening a separate issue ticket for the out of subjects issue.

**Comment by AnLand** [comment] 2016-02-19 19:25
Interestingly in the video, @jwidness posted, the classification count (11) does not match the counter of the classifications: blank (3) and chimpanzee (10).

**Comment by AnLand** [comment] 2016-02-19 20:34
@srallen Now, I had this video http://talk.chimpandsee.org/#/subjects/ACP00084qp for classification. I classified once. Got it immediately again, the "Finish" button was stalled and I hit him several times. Now I have this video in my "Recents" 12 times and the classification counter is at 12. So I did all these classifications on this video. I hit (for testing) the Finish button two more times and now the classification counter is at 14. This is a serious bug, I think.

**Comment by yshish** [comment] 2016-02-19 20:45
It is exactly what was happening to me.

**Comment by srallen** [comment] 2016-02-19 21:24
@AnLand thanks for letting me know. If it happens again, could you open up your browser console and let me know what errors you see? Thanks.

**Comment by AnLand** [comment] 2016-02-20 10:48
@srallen It happened again with this video: http://talk.chimpandsee.org/#/subjects/ACP0007k3s
I classfied once, got it a second time immediately and the Finish button was stalled. My classifications counted all I tried a bit and subject is now retired (but at least somebody else also classified and said 'blank').

**TypeError: Subject.current is null
http://www.chimpandsee.org/main.385b6d93989a5179c4ed.js line 18 > eval**

I did not see this yesterday (because my screen is not that big), but directly under the annotation results is the "We're out of data" message displayed.

Hope that helps.

**Comment by mimiarandjelovic** [comment] 2016-02-20 13:15
Hi - Can we re run the videos once this bug is fixed please? otherwise we won't be able to use the output data, Should we maybe pause classifications until it is fixed?

**Comment by srallen** [comment] 2016-02-20 16:06
@mimiarandjelovic and @AnLand, I've cleaned up some of the code in the summary and with the social media sharing component and this should at least enable the summary to be loaded when `Subject.current` is null, but the talk link will be broken. I've opened up #101 and pinged some other developers about the out of subjects response since we shouldn't be getting that response and I think it's related if not the cause of the issues.

**Comment by yshish** [comment] 2016-02-20 18:10
This is what my browser console says while classifying (while there is no repeating experience), is it OK?
![](https://lh3.googleusercontent.com/-2geMljb1apw/VsirkqLF-GI/AAAAAAAAIws/IF2ybWhqqKY/s0-Ic42/ysh_2016-02-20_18-49-02.png)
And when I want to discuss the video, it gets me here: http://talk.chimpandsee.org/#/subjects/null

**Comment by jwidness** [comment] 2016-02-22 03:36
I got the out of data message, but the console didn't show the same errors.
<img width="960" alt="error" src="https://cloud.githubusercontent.com/assets/13769652/13208812/b929d2b8-d8ea-11e5-9a1c-427c3083c94c.png">

**Comment by srallen** [comment] 2016-02-22 15:18
@jwidness, do you have a browser plugin that blocks google analytics? Those errors are just reporting that your browser is blocking the google analytics that is setup. I've opened a separate issue, #101, for the incorrect out of subjects response.

**Comment by jwidness** [comment] 2016-02-22 15:20
Yes, sorry, those messages were definitely from my extensions.  I just meant that I wasn't getting the errors that @yshish was reporting.

**Comment by jwidness** [comment] 2016-02-22 15:21
I don't know whether this is relevant or not, but the video was one I marked "Nothing here" on.  Not sure what the changes about the code.

**Comment by jwidness** [comment] 2016-02-22 15:24
I suppose I could also say that I'm sure it added two "blanks" to the counters on the video -- one for each time I clicked "Nothing here".

**Comment by srallen** [comment] 2016-02-22 16:24
Clicking "Nothing here" creates and saves a classification with a "nothing here" annotation and immediately calls for the next subject. Today, I'm going to work on making sure the old video and images do not display if an out of subject message returns.

**Comment by yshish** [comment] 2016-02-22 16:29
I haven't experienced any repetitions since the fix but then I got this video today http://talk.chimpandsee.org/#/subjects/ACP0007ey9  to classify for the second time although I did classify it 3 days ago already - as you can see there is my comment with the tags from Feb 19th.

As it wasn't repeated in a row, the Finish button did no problems and the browser console showed no errors. This kind of repetitions is more common and is not easily provable for me as I don't see the previous classification among the most recent classifications on my profile. But it does happen (and it isn't a problem of C&S only).

Can you please check out the record whether it really shows two classifications from yshish for that single video so we were sure it came twice? http://talk.chimpandsee.org/#/subjects/ACP0007ey9

**Comment by yshish** [comment] 2016-02-22 17:00
Another repeating reported by Boleyn 2 minutes ago: http://talk.chimpandsee.org/#/subjects/ACP0007p0n

**Comment by srallen** [comment] 2016-02-22 19:06
Ok, the out of subjects issue is fixed and I think I've done enough refactoring to fix the issues with the summary page to fix the issues of the next subject loading. I'll leave this open still in case there are any more reports related to the initial error reports.

@yshish those kind of duplicates will be harder for us to track down and it sounds like those kinds of duplicates are unrelated to the errors in this thread.

**Comment by yshish** [comment] 2016-02-22 19:14
Cool. Thank you! 

Actually the last mentioned repetition is the same type as I started this issue thread with (see the list of 5 examples of repeating in my first post). We started talking about the other type (two repeating videos in a row with a Finish button problem) in the 2nd post :) 

Anyway, shall I create a separate issue thread for those complicated you are not able to solve now or keep them here?

**Comment by srallen** [comment] 2016-02-22 19:19
Yeah I'd like to have a separate issue for duplicate subject that aren't breaking the interface -- it helps me keep better track. Getting truly duplicate videos in the queue is from a different unknown cause than from the issues that ended up being discussed here such as the broken summary page and out of subjects error. Thanks.

**Comment by srallen** [comment] 2016-02-24 19:25
Closing since there hasn't been any more reports of broken interfaces.

**Closed by srallen** 2016-02-24 19:25 UTC
